# Generated by Django 3.1.1 on 2020-12-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='completed_script_ids',
            field=models.CharField(max_length=500),
        ),
    ]
