# Generated by Django 3.1.1 on 2020-09-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='name2',
        ),
    ]
