# Generated by Django 3.1.1 on 2020-09-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0003_auto_20200926_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlevel',
            old_name='hit_dice',
            new_name='hit_dice_type',
        ),
    ]
