# Generated by Django 3.1.2 on 2020-10-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0005_auto_20200926_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='damage_type',
            field=models.CharField(choices=[('Bludgeoning', 'Bludgeoning'), ('Piercing', 'Piercing'), ('Slashing', 'Slashing'), ('Force', 'Force'), ('Fire', 'Fire'), ('Frost', 'Frost'), ('Lightning', 'Lightning'), ('Poison', 'Poison'), ('Acid', 'Acid'), ('Necrotic', 'Necrotic'), ('Radiant', 'Radiant'), ('Healing', 'Healing')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='damage_type',
            field=models.CharField(choices=[('Bludgeoning', 'Bludgeoning'), ('Piercing', 'Piercing'), ('Slashing', 'Slashing'), ('Force', 'Force'), ('Fire', 'Fire'), ('Frost', 'Frost'), ('Lightning', 'Lightning'), ('Poison', 'Poison'), ('Acid', 'Acid'), ('Necrotic', 'Necrotic'), ('Radiant', 'Radiant'), ('Healing', 'Healing')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(choices=[('Abjuration', 'Abjuration'), ('Conjuration', 'Conjuration'), ('Divination', 'Divination'), ('Enchantment', 'Enchantment'), ('Evocation', 'Evocation'), ('Illusion', 'Illusion'), ('Necromancy', 'Necromancy'), ('Transmutaion', 'Transmutation')], max_length=30, null=True),
        ),
    ]
