# Generated by Django 3.1.2 on 2020-10-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0006_auto_20201023_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_finness',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
