# Generated by Django 3.1.2 on 2020-10-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0007_item_has_finness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='has_finness',
            new_name='has_finesse',
        ),
    ]
