# Generated by Django 3.1.1 on 2021-04-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0008_auto_20201023_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='class_type',
            field=models.CharField(choices=[('Cleric', 'Cleric'), ('Fighter', 'Fighter'), ('Rogue', 'Rogue'), ('Wizard', 'Wizard')], max_length=30, null=True),
        ),
    ]
