# Generated by Django 3.1.1 on 2020-09-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='armor_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charisma_save',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution_save',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity_save',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hit_dice_total',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hit_dice_type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intellegence_save',
        ),
        migrations.RemoveField(
            model_name='character',
            name='passive_insight',
        ),
        migrations.RemoveField(
            model_name='character',
            name='passive_investigation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='passive_perception',
        ),
        migrations.RemoveField(
            model_name='character',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength_save',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom_save',
        ),
    ]
