# Generated by Django 3.1.1 on 2020-09-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0005_auto_20200926_1817'),
        ('character', '0003_auto_20200926_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='item',
        ),
        migrations.AddField(
            model_name='character',
            name='item',
            field=models.ManyToManyField(to='ref_data.Item'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell',
        ),
        migrations.AddField(
            model_name='character',
            name='spell',
            field=models.ManyToManyField(to='ref_data.Spell'),
        ),
    ]
