# Generated by Django 3.1.1 on 2020-09-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20200926_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='spell',
            new_name='spells',
        ),
    ]
