# Generated by Django 3.1.1 on 2020-09-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20200926_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='intellegence',
            new_name='intelligence',
        ),
    ]
