# Generated by Django 3.1.2 on 2020-10-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20200926_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
