# Generated by Django 3.1.1 on 2020-12-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_character_armor_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
