# Generated by Django 3.1.1 on 2020-12-21 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
        ('character', '0008_character_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.gamedata'),
        ),
    ]
