# Generated by Django 3.1.1 on 2021-01-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0003_auto_20210103_1621'),
        ('ref_data', '0008_auto_20201023_2222'),
        ('character', '0009_character_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC_Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('hit_dice_current', models.IntegerField()),
                ('hit_points_total', models.IntegerField()),
                ('hit_points_current', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('items', models.ManyToManyField(to='ref_data.Item')),
                ('spells', models.ManyToManyField(to='ref_data.Spell')),
            ],
            options={
                'db_table': 'npc_character',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PC_Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('hit_dice_current', models.IntegerField()),
                ('hit_points_total', models.IntegerField()),
                ('hit_points_current', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('class_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ref_data.classlevel')),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.gamedata')),
                ('items', models.ManyToManyField(to='ref_data.Item')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ref_data.race')),
                ('spells', models.ManyToManyField(to='ref_data.Spell')),
            ],
            options={
                'db_table': 'pc_character',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
