# Generated by Django 3.1.1 on 2021-01-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20210116_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc_character',
            old_name='game_id',
            new_name='game',
        ),
    ]
