# Generated by Django 3.1.1 on 2021-04-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0003_auto_20210103_1621'),
        ('character', '0011_auto_20210116_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc_character',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_data.gamedata'),
        ),
    ]
